#!/bin/bash

README="README.md"
hash markdown 2>/dev/null 2>&1 || { echo >&2 "I require markdown but it's not installed.  Aborting."; exit 1; }
hash lynx 2>/dev/null 2>&1 || { echo >&2 "I require lynx but it's not installed.  Aborting."; exit 1; }

pandoc -f markdown -t html -s ["README.md"]
